# keywords to search for audio and speech processing
keywords:
    "Speech Recognition":
        filters: ["Speech Recognition", "ASR", "Automatic Speech Recognition", 
                  "Speech-to-Text", "Voice Recognition", "Speech Emotion Recognition", 
                  "Emotion Recognition", "Affective Computing", "Emotional Speech", 
                  "Sentiment Analysis", "Speaker Recognition", "Speaker Identification", 
                  "Speaker Verification", "Voice Biometrics", "Speaker Diarization"]
        category: "Speech"
    "Speech Synthesis":
        filters: ["Speech Synthesis", "TTS", "Text-to-Speech", "Voice Synthesis",
                  "Neural Vocoder", "Speech Generation"]
        category: "Speech"
    "Speech Enhancement":
        filters: ["Speech Enhancement", "Noise Reduction", "Speech Denoising",
                  "Audio Enhancement", "Speech Separation"]
        category: "Speech"
    "Audio Classification":
        filters: ["Audio Classification", "Sound Classification", "Audio Scene Classification",
                  "Environmental Sound", "Audio Event Detection"]
        category: "Speech"
    "Music Information Retrieval":
        filters: ["Music Information Retrieval", "MIR", "Music Analysis", "Audio Music",
                  "Chord Recognition"]
        category: "Music"
    "Music Generation":
        filters: ["Music Generation", "Song Generation", "Music Synthesis", "AI Music",
                  "Melody Generation", "Music Composition", "Audio Music Generation"]
        category: "Music"
    "Audio Codec":
        filters: ["Audio Codec", "Audio Compression", "Neural Audio Codec",
                  "Speech Codec", "Audio Coding"]
        category: "Speech"
    "Image Generation":
        filters: ["Image Generation", "Text-to-Image", "Image Synthesis", "Diffusion Models",
                  "GAN", "Generative Adversarial Networks", "DALL-E", "Stable Diffusion"]
        category: "Image"
    "Video Generation":
        filters: ["Video Generation", "Text-to-Video", "Video Synthesis", "Video Diffusion",
                  "Temporal Modeling", "Motion Generation", "Video Prediction"]
        category: "Image"
    "Multimodal Generation":
        filters: ["Multimodal Generation", "Vision-Language Models", "CLIP", "Cross-modal",
                  "Audio-Visual Generation", "Multimodal Synthesis"]
        category: "Image"