all_topic: ['Audio Representation Learning','Speech Recognition', 'Speech Synthesis', 'Speech Enhancement', 'Audio Classification', 'Music Information Retrieval', 'Music Generation', 'Audio Codec', 'Image Generation', 'Video Generation','Other']
all_category: ['Music', "Speech", "Image&Video", "Other"]
whitelist_subjects: ['cs.SD', 'eess.AS']